on:
  discussion_comment:
    types: [created]

name: "Vouch - Manage by Discussion"

concurrency:
  group: vouch-manage
  cancel-in-progress: false

permissions:
  contents: write
  discussions: write
  pull-requests: write

jobs:
  manage:
    runs-on: namespace-profile-ghostty-xsm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: mitchellh/vouch/action/manage-by-discussion@6803dde571265e13489c3f118200f60b6ab59e4d # v1.3.1
        with:
          discussion-number: ${{ github.event.discussion.number }}
          comment-node-id: ${{ github.event.comment.node_id }}
          vouch-keyword: "!vouch"
          denounce-keyword: "!denounce"
          unvouch-keyword: "!unvouch"
          pull-request: "true"
          merge-immediately: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
