on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at midnight UTC
  workflow_dispatch:

name: "Vouch - Sync CODEOWNERS"

concurrency:
  group: vouch-manage
  cancel-in-progress: false

jobs:
  sync:
    runs-on: namespace-profile-ghostty-xsm
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.VOUCH_APP_ID }}
          private-key: ${{ secrets.VOUCH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: mitchellh/vouch/action/sync-codeowners@daa39f90448eb4054ad334d7f53959a7efb5005b # v1.4.0
        with:
          repo: ${{ github.repository }}
          pull-request: "true"
          merge-immediately: "true"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
