on:
  issues:
    types: [opened, reopened]

name: "Vouch - Check Issue"

permissions:
  contents: read
  issues: write

jobs:
  check:
    runs-on: namespace-profile-ghostty-xsm
    steps:
      - uses: mitchellh/vouch/action/check-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          auto-close: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
