on:
  pull_request_target:
    types: [opened, reopened]

name: "Vouch - Check PR"

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    runs-on: namespace-profile-ghostty-xsm
    steps:
      - uses: mitchellh/vouch/action/check-pr@8c4f29bb7f2ddfa0b8dbc1bb6575e3f27c95d10a # v1.2.0
        with:
          pr-number: ${{ github.event.pull_request.number }}
          auto-close: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
