on:
  pull_request_target:
    types: [opened, reopened]

name: "Vouch - Check PR"

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    runs-on: namespace-profile-ghostty-xsm
    steps:
      - uses: mitchellh/vouch/action/check-pr@v1
        with:
          pr-number: ${{ github.event.pull_request.number }}
          auto-close: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
